Fix the spelling mistake in the git commit message
Care-X/landing-page pull request #92
Opened 2023-02-21 14:07 UTC by Prasadkpd

## Purpose

The purpose of this Pull Request is to fix #91

## Goals

Fixing the spelling mistake in the git commit message in readme.md file

## Approach

Fixed the spelling mistake in the git commit message in readme.md file

### Screenshots

  
<img width="861" alt="image" src="https://user-images.githubusercontent.com/77828396/220367012-232f37b2-62db-4075-8555-76d66f2ba59c.png">

### Preview Link

https://github.com/Prasadkpd/carx-landing-page/tree/fixSpell

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2023-02-21 16:27 UTC, YoshithaRathnayake requested changes

2023-02-21 16:27 UTC, YoshithaRathnayake commented on README.md
> +git commit -m 'Your Messege'
It should be `Message`
```suggestion
git commit -m 'Your Message'
```

2023-02-21 16:27 UTC, YoshithaRathnayake commented on README.md
> +git commit -m 'Your Messege'
@Prasadkpd

2023-02-22 05:31 UTC, Prasadkpd commented on README.md
> +git commit -m 'Your Messege'
Done

2023-02-23 09:17 UTC, YoshithaRathnayake approved these changes
Thank you @Prasadkpd 
Can you merge this @sathsarabandaraj

2023-02-23 11:33 UTC, merged